### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by NotSoMik** [JosephJoshua/potato-salad#1]
Hello, this project is amazing, also the tictactoe command, can you make more games with canvas and buttons such as connect4, hangman, snake or add the home button in the pagination system :). It will be cool

**Comment by JosephJoshua** [comment]
Hey! Thanks for the ideas. We'll try our best to add those!

**Comment by NotSoMik** [comment]
Nice, Thanks for considering my idea

**Comment by GioGio03** [comment]
Do you have a discord server because I wanna ask you something ^^. however in the tictactoe command you can add that when a user clicks the x button it changes color and becomes red and for the o button it becomes blue

**Comment by NotSoMik** [comment]
Yea it will be cool

**Comment by JosephJoshua** [comment]
We don't have a Discord server for support right now, but you can contact me through DMs. My Discord tag is jsph273#3683.
Also, thanks for the suggestion! We also thought that it was a bit hard to tell when it switches turns.

**Comment by GioGio03** [comment]
Oh alright

**Comment by NotSoMik** [comment]
Now the tictactoe command suppors 5x5 or the board is only 5x5

**Comment by Sherrin0825** [comment]
Hi @NotSoMik, the `/tictactoe` command supports 1x1 to 5x5 - bigger boards are not supported due to Discord's restriction: [An Action Row can contain up to 5 buttons](https://discord.com/developers/docs/interactions/message-components#buttons)

**Comment by NotSoMik** [comment]
Amd how can we choose for example 2×2

**Comment by Sherrin0825** [comment]
You could manually change the `BOARD_SIZE` variable in the [source code](https://github.com/JosephJoshua/potato-salad/blob/a1fc865fc84f51f711ae31d8b78996f95ba8e5a8/commands/games/tictactoe.js#L5). Board sizes other than 3x3 are meant to be a hidden feature so it's not part of the slash command.

**Comment by NotSoMik** [comment]
Oh ok thanks

**Comment by NotSoMik** [comment]
yo about the ttt emojis instead of X can we use ❌ or ⭕. I want to get a confirmation from you

**Comment by Sherrin0825** [comment]
You could, but it does not look as good.

**Comment by NotSoMik** [comment]
Yea lol
